{application,shared_assigns,
             [{config_mtime,1751892881},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,phoenix_live_view,
                             phoenix]},
              {description,"A React Context-like library for Phoenix LiveView that eliminates prop drilling\nby allowing components to subscribe to specific context values and automatically\nre-render when those contexts change.\n"},
              {modules,['Elixir.SharedAssigns',
                        'Elixir.SharedAssigns.Component',
                        'Elixir.SharedAssigns.Consumer',
                        'Elixir.SharedAssigns.Consumer.Component',
                        'Elixir.SharedAssigns.Helpers',
                        'Elixir.SharedAssigns.Provider',
                        'Elixir.SharedAssigns.PubSubConsumer',
                        'Elixir.SharedAssigns.PubSubProvider']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
